### ISSUE TITLE
Configurable UA for HTTP checks

### ISSUE THREAD

**Issue by jnewland** [joewilliams/nugget#7]
It would be cool to be able to use the user-agent string to provide developers with information about what these checks are and where they could adjust their behavior.

**Comment by joewilliams** [comment]
Hey @jnewland this is like totally tardy but this is something you can do in nugget already! Just specify the user agent headers in the request definition.

``````
"github_http": {
    "type": "http",

    "request": {
      "timeout": 15,
      "url": "https://github.com/status",
      "method": "get",
      "headers": {
        "user-agent": "this is a cool user agent",
      }
    },

    "response": {
      "response_code": 200,
      "total_time": 10
    }
  }
``````

**Comment by gorsuch** [comment]
CLOSED

**Comment by jnewland** [comment]
Noice, thanks @joewilliams.

:wave: at @gorsuch :)
